### ISSUE TITLE
Refine criteria distinguishing active users

### ISSUE THREAD

**Issue by Comeani** [pitt-crc/keystone-api#307]
In a discussion today about relieving the core site of its role in tracking users, their delegate status, etc. Fangping asked about the current criteria for making a user as `inactive` such that operations could be performed across a user list filtered down to active users.

There appears to be a `Is active` field for each User under their permissions tab.

It may be that we'd want to use LDAP instead to track this kind of value, but whether it's set there or in Keystone, the comment was to make this dynamic to whether or not the user has representation in Pitt Active Directory.

**Comment by djperrefort** [comment]
@Comeani this sounds like a feature request, but I'm not sure what the requested functionality is. Can you clarify?

Keystone already supports syncing the `is_active` field against an LDAP field. There is no functionality to mark missing users as inactive, only to delete them. Marking as inactive is an easy to implement alternative. Is that what @fangpingmu is asking for?
