### ISSUE TITLE
Make Allocation Request Description field optional

### ISSUE THREAD

**Issue by Comeani** [pitt-crc/keystone-api#325]
After demoing the Allocation Request ingest process to Melissa today, she made the comment that the description field for any given request is generally not super important, and would be duplicating information found in the submission file in many cases (the project abstract for example).

With this, she said that if it meant less copy pasting, we could allow that field to be blank / optional when saving the allocation.

**Comment by djperrefort** [comment]
Most of the duplication has to do with our business workflow. The description field is intended for the justification, where as the attachment field is intended for supporting documents (e.g., diagrams). It sounds like it is currently being used the other way around.
